import {
  BiCheckCircle,
  BiCheckDouble,
  BiGrid,
  BiTimer,
  BiUserPin,
} from "react-icons/bi";
import {
  FaCalendarAlt,
  FaList,
  FaFileMedicalAlt,
  FaCheckCircle,
  FaTimesCircle,
  FaTimes,
  FaUser,
} from "react-icons/fa";

export const DoctorResources = [
  {
    path: "dashboard",
    icon: BiGrid,
    metrics: [
      {
        name: "Appointments",
        units: [
          {
            title: "All Appointments",
            path: "appointments",
            icon: FaCalendarAlt,
            dataSource: "https://ehcs.onrender.com/appointments/count",
            dataType: "count",
            color: "blue",
            seeMore: true,
            onClick: () => {
              console.log("Clicked on Appointments");
            },
            redirectLink: "/appointments",
            show: true,
          },
          {
            title: "Scheduled Appointments",
            path: "scheduled-appointments",
            icon: BiTimer,
            dataSource:
              "https://ehcs.onrender.com/appointments/count?status=Scheduled",
            dataType: "fieldQuery",
            field: "status",
            value: "Scheduled",
            color: "lightBlue",
            seeMore: true,
            onClick: () => {
              console.log("Clicked on Patients");
            },
            redirectLink: "/patients",
            show: true,
          },
          {
            title: "Confirmed Appointments",
            path: "confirmed-appointments",
            icon: FaCheckCircle,
            dataSource:
              "https://ehcs.onrender.com/appointments/count?status=Confirmed",
            dataType: "fieldQuery",
            field: "status",
            value: "Confirmed",
            color: "lime",
            seeMore: true,
            onClick: () => {
              console.log("Clicked on Confirmed Appointments");
            },
            redirectLink: "/confirmed-appointments",
            show: true,
          },
          {
            title: "Completed Appointments",
            path: "completed-appointments",
            icon: FaCheckCircle,
            dataSource:
              "https://ehcs.onrender.com/appointments/count?status=Completed",
            dataType: "fieldQuery",
            field: "status",
            value: "Completed",
            color: "green",
            seeMore: true,
            onClick: () => {
              console.log("Clicked on Completed Appointments");
            },
            redirectLink: "/completed-appointments",
            show: true,
          },
          {
            title: "Cancelled Appointments",
            path: "cancelled-appointments",
            icon: FaTimesCircle,
            dataSource:
              "https://ehcs.onrender.com/appointments/count?status=Cancelled",
            dataType: "fieldQuery",
            field: "status",
            value: "Cancelled",
            color: "red",
            seeMore: true,
            onClick: () => {
              console.log("Clicked on Cancelled Appointments");
            },
            redirectLink: "/cancelled-appointments",
            show: true,
          },
        ],
      },
    ],
  },

  {
    path: "scheduled-appointments",
    dataSource: "https://ehcs.onrender.com/appointments",
    icon: BiTimer,
    sidePanel: false,
    type: "crud",
    // add: true,
    view: true,
    edit: true,
    //update: true,
    //delete: true,
    fetchDataByQuery: true,
    queryField: "status",
    queryValue: "Scheduled",
    menu: { name: "Appointments", icon: FaList },
    schema: [
      {
        name: "patient",
        title: "Patient",
        type: "text",
      },
      { name: "doctor", title: "Doctor", type: "text" },
      { name: "date", title: "Appointment Date", type: "date" },
      {
        name: "status",
        title: "Status",
        type: "select",
        options: [
          { label: "Scheduled", value: "Scheduled" },
          { label: "Confirmed", value: "Confirmed" },
          { label: "Completed", value: "Completed" },
          { label: "Cancelled", value: "Cancelled" },
        ],
      },
    ],
  },
  {
    path: "confirmed-appointments",
    dataSource: "https://ehcs.onrender.com/appointments",
    icon: BiCheckCircle,
    sidePanel: false,
    type: "crud",
    add: false,
    view: true,
    edit: true,
    //update: true,
    //delete: true,
    fetchDataByQuery: true,
    queryField: "status",
    queryValue: "Confirmed",
    menu: { name: "Appointments", icon: FaList },
    schema: [
      {
        name: "patient",
        title: "Patient",
        type: "text",
      },
      { name: "doctor", title: "Doctor", type: "text" },
      { name: "date", title: "Appointment Date", type: "date" },
      {
        name: "status",
        title: "Status",
        type: "select",
        options: [
          { label: "Scheduled", value: "Scheduled" },
          { label: "Confirmed", value: "Confirmed" },
          { label: "Completed", value: "Completed" },
          { label: "Cancelled", value: "Cancelled" },
        ],
      },
    ],
  },
  {
    path: "Completed-appointments",
    dataSource: "https://ehcs.onrender.com/appointments",
    icon: BiCheckDouble,
    sidePanel: false,
    type: "crud",
    add: false,
    view: true,
    edit: true,
    //update: true,
    //delete: true,
    fetchDataByQuery: true,
    queryField: "status",
    queryValue: "Completed",
    menu: { name: "Appointments", icon: FaList },
    schema: [
      {
        name: "patient",
        title: "Patient",
        type: "text",
      },
      { name: "doctor", title: "Doctor", type: "text" },
      { name: "date", title: "Appointment Date", type: "date" },
      {
        name: "status",
        title: "Status",
        type: "select",
        options: [
          { label: "Scheduled", value: "Scheduled" },
          { label: "Confirmed", value: "Confirmed" },
          { label: "Completed", value: "Completed" },
          { label: "Cancelled", value: "Cancelled" },
        ],
      },
    ],
  },
  {
    path: "Cancelled-appointments",
    dataSource: "https://ehcs.onrender.com/appointments",
    icon: FaTimes,
    sidePanel: false,
    type: "crud",
    add: false,
    view: true,
    edit: true,
    //update: true,
    // delete: true,
    fetchDataByQuery: true,
    queryField: "status",
    queryValue: "Cancelled",
    menu: { name: "Appointments", icon: FaList },
    schema: [
      {
        name: "patient",
        title: "Patient",
        type: "text",
      },
      { name: "doctor", title: "Doctor", type: "text" },
      { name: "date", title: "Appointment Date", type: "date" },
      {
        name: "status",
        title: "Status",
        type: "select",
        options: [
          { label: "Scheduled", value: "Scheduled" },
          { label: "Confirmed", value: "Confirmed" },
          { label: "Completed", value: "Completed" },
          { label: "Cancelled", value: "Cancelled" },
        ],
      },
    ],
  },
  {
    path: "followups",
    dataSource: "https://ehcs.onrender.com/followups",
    icon: FaFileMedicalAlt,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: { name: "resources", icon: FaList },
    schema: [
      { name: "appointmentId", title: "Appointment ID", type: "text" },
      {
        name: "patientId",
        title: "Patient ID",
        type: "text",
      },
      { name: "doctorId", title: "Doctor ID", type: "text" },
      { name: "date", title: "Follow-up Date", type: "datetime" },
      { name: "notes", title: "Notes", type: "textarea" },
    ],
  },
  {
    path: "profile",
    dataSource: "https://ehcs.onrender.com/users",
   
    icon: FaUser,
    sidePanel: false,
    type: "singleton",
    queryField: "_id",
    schema: [
      { name: "Image", title: "Image", type: "file" },
      { name: "username", title: "Username", type: "text" },
      { name: "email", title: "Email", type: "text" },
      { name: "firstName", title: "First Name", type: "text" },
      { name: "lastName", title: "Last Name", type: "text" },
      { name: "dateOfBirth", title: "Date Of Birth", type: "date" },
    ],
  },
];
